### ISSUE TITLE
Poco/Delegate.h not found

### ISSUE THREAD

**Issue by nightshining** [arturoc/ofxTween#19]
Building for OF 10 (iOS version) + iOS 12 with Xcode 10 returns error 'Poco/Delegate.h' not found.

**Comment by moebiussurfing** [comment]
Look for an update addon ofxTeeen2

**Comment by moebiussurfing** [comment]
ofxEasing is the new tweener if you are starting a new project.
But I told you ofxTween2 because maybe you are updating an old project where you used ofxTween

**Comment by arturoc** [comment]
Yes if you are using a new project is recommended to use ofxEasing since this is deprecated but if you want to compile an old project that uses this addon with 0.10 then you need to also include ofxPoco in your project
